#Gradle
org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6G
kotlin.native.compiler.jvmArgs=-Xmx8G

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

#MPP
kotlin.mpp.enableCInteropCommonization=true

signing.gnupg.executable=gpg

#Dokka
org.jetbrains.dokka.classpath.useNativeDistributionAccessor=true