name: mockzilla_ios
description: The iOS implementation for the mockzilla plugin.
version: 1.0.0 # x-release-please-version
homepage: https://apadmi-engineering.github.io/Mockzilla/
repository: https://github.com/Apadmi-Engineering/Mockzilla
issue_tracker: https://github.com/Apadmi-Engineering/Mockzilla/issues
documentation: https://apadmi-engineering.github.io/Mockzilla/
topics:
  - http
  - server
  - tool
  - mockzilla

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  mockzilla_platform_interface: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^12.0.1
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: mockzilla
    platforms:
      ios:
        dartPluginClass: MockzillaIos
        pluginClass: MockzillaIosPlugin