name: mockzilla_ios
description: The Android implementation for the mockzilla plugin.
version: 0.1.0
homepage: https://apadmi-engineering.github.io/Mockzilla/
repository: https://github.com/Apadmi-Engineering/Mockzilla
issue_tracker: https://github.com/Apadmi-Engineering/Mockzilla/issues
documentation: https://apadmi-engineering.github.io/Mockzilla/
topics:
  - http
  - server
  - tool
  - mockzilla

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  # TODO: Local dependencies used for ease of development, these should be regular dependencies
  # once this plugin is hosted.
  mockzilla_platform_interface:
    path: ../mockzilla_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^12.0.1
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: mockzilla
    platforms:
      ios:
        dartPluginClass: MockzillaIos
        pluginClass: MockzillaIosPlugin