package com.apadmi.mockzilla.codegen.file_builders.dart

import com.apadmi.mockzilla.codegen.data.EndpointSpec
import com.apadmi.mockzilla.codegen.data.ExampleResponse

fun generateDartSource(endpoints: Array<EndpointSpec>): String {
    val buffer = StringBuffer()
    buffer.appendLine("// GENERATED CODE")
    buffer.appendLine("// Generated by Mockzilla")
    buffer.appendLine()
    buffer.appendLine("import 'package:mockzilla/mockzilla.dart';")
    buffer.appendLine()

    buffer.appendLine("final mockzillaConfig = MockzillaConfig(")
    buffer.appendLine("endpoints: [")

    for (endpoint in endpoints) {
        buffer.appendLine(endpointFragment(endpoint))
    }
    buffer.appendLine("]);")

    return buffer.toString()
}

internal fun endpointFragment(e: EndpointSpec): String = """
    EndpointConfig(
      name: '${(e.method.name.uppercase() + e.path.replace("/", " ")).toEndpointName()}',
      endpointMatcher: (request) =>
          request.method == HttpMethod.${e.method.name.lowercase()} &&
          request.uri.endsWith('${e.path}'),
      defaultHandler: (request) => ${responseExpression(e.successResponse)},
      errorHandler: (request) => ${responseExpression(e.errorResponse)},
      dashboardOptionsConfig: DashboardOptionsConfig(
        presets: [${e.otherResponses.joinToString(",") { presetFragment(it) }}],
      ),
    ),"""

//TODO: can we get descriptions? Also needed in other generators
internal fun presetFragment(r: ExampleResponse): String = """
          DashboardOverridePreset(
            name: '${r.name.escapeForDartLiteral()}',
            description: null,
            response: ${responseExpression(r)},
          )"""

internal fun responseExpression(v: ExampleResponse): String {
    return "MockzillaHttpResponse(statusCode: ${v.statusCode}, body: '${v.bodyValue.escapeJsonForDartLiteral()}')"
}

fun String.toEndpointName(): String {
    return escapeForDartLiteral().replace("*", " ").replace(":", " ")
}

internal fun String.escapeForDartLiteral(): String {
    return replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\$", "\\\$")
        .replace("\n", " ")
        .replace("\r", "\\r")
}

internal fun String.escapeJsonForDartLiteral(): String {
    return replace("'", "\\'").replace("\$", "\\\$")
}

