[versions]

# Kotlin
adam = "0.5.10" # https://github.com/Malinskiy/adam
jmdns = "3.6.3" # https://github.com/jmdns/jmdns
kotlin = "2.4.10" # https://github.com/JetBrains/kotlin
agp = "9.3.2" # https://developer.android.com/build/releases/gradle-plugin
kotlinxBrowser = "0.5.0" # https://github.com/Kotlin/kotlinx-browser
ksp = "2.3.11" # https://github.com/google/ksp

# Logging
kermit = "2.1.0" # https://github.com/touchlab/Kermit

# Config
buildKonfig = "0.22.0" # https://github.com/yshrsmz/BuildKonfig

# Documentation
dokka = "2.2.0" # https://github.com/Kotlin/dokka

# Localization
lyricist = "1.9.0" # https://github.com/adrielcafe/lyricist

# Networking
ktor = "3.5.2" # https://github.com/ktorio/ktor

# Compose
compose = "1.11.1" # https://github.com/JetBrains/compose-multiplatform

# DI
koin = "4.2.2" # https://github.com/InsertKoinIO/koin

# KotlinX
kotlinx-coroutines = "1.11.0" # https://github.com/Kotlin/kotlinx.coroutines
kotlinx-datetime = "0.8.0" # https://github.com/Kotlin/kotlinx-datetime
kotlinx-serialization = "1.11.0" # https://github.com/Kotlin/kotlinx.serialization

# AndroidX
lifecycle = "2.10.0" # https://developer.android.com/jetpack/androidx/releases/lifecycle
compose-activity = "1.13.0" # https://developer.android.com/jetpack/androidx/releases/activity
material3 = "1.9.0"
materialIconsExtended = "1.7.3"
mockk = "1.14.11"
navigationCompose = "2.9.2"
playServicesAdsIdentifier = "18.3.0"

# Semantic Versioning
semver = "3.1.0" # https://github.com/z4kn4fein/kotlin-semver

# Code Formatting
spotless = "8.10.0" # https://github.com/diffplug/spotless

# Testing
kover = "0.9.9" # https://github.com/Kotlin/kotlinx-kover
swaggerParser = "2.1.47" # https://github.com/swagger-api/swagger-parser/releases
turbine = "1.2.1" # https://github.com/cashapp/turbine
junit = "1.3.0" # https://developer.android.com/jetpack/androidx/releases/test
testParamInjector = "1.22" # https://github.com/google/TestParameterInjector

# Publishing
conveyor = "2.0" # https://github.com/hydraulic-software/conveyor
vanniktech-publish = "0.37.0" # https://github.com/vanniktech/gradle-maven-publish-plugin

# License attribution
aboutlibraries = "15.1.1" # https://github.com/mikepenz/AboutLibraries/releases

[libraries]

# Compose & Material
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity"  }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
desktop-jvm-macos-arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-arm64", version.ref = "compose" }
desktop-jvm-macos-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-x64", version.ref = "compose" }
desktop-jvm-linux-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-x64", version.ref = "compose" }
desktop-jvm-windows-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "compose" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swaggerParser" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }

# Android Lifecycle
androidx-lifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Logging
jmdns-jmdns = { module = "org.jmdns:jmdns", version.ref = "jmdns" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# Kotlin
kotlinx-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref="kotlinx-coroutines" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }

# Ktor
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Utils
adam = { module = "com.malinskiy.adam:adam", version.ref = "adam" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }

# DI
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
testParamInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParamInjector" }
turbine = { module="app.cash.turbine:turbine", version.ref = "turbine" }

# Localization
lyricist-library = { module = "cafe.adriel.lyricist:lyricist", version.ref = "lyricist" }
lyricist-processor = { module = "cafe.adriel.lyricist:lyricist-processor", version.ref = "lyricist" }

# License attribution
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
android-app = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
conveyor = { id = "dev.hydraulic.conveyor", version.ref = "conveyor" }
vanniktechPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
