name: mockzilla_platform_interface
description: A common interface for the mockzilla plugin.
# x-release-please-start-version
version: 1.0.2
# x-release-please-end
homepage: https://apadmi-engineering.github.io/Mockzilla/
repository: https://github.com/Apadmi-Engineering/Mockzilla
issue_tracker: https://github.com/Apadmi-Engineering/Mockzilla/issues
documentation: https://apadmi-engineering.github.io/Mockzilla/
topics:
  - http
  - server
  - tool
  - mockzilla

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter

  # Interface
  plugin_platform_interface: ^2.1.8

  # Models
  freezed_annotation: ^3.0.0

dev_dependencies:
  # Models
  freezed: ^3.0.0
  build_runner: ^2.4.6

  # Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0