name: mockzilla_platform_interface
description: A common interface for the mockzilla plugin.
# x-release-please-start-version
version: 2.0.1
# x-release-please-end
homepage: https://mockzilla.apadmi.dev/
repository: https://github.com/Apadmi-Engineering/Mockzilla
issue_tracker: https://github.com/Apadmi-Engineering/Mockzilla/issues
documentation: https://mockzilla.apadmi.dev/
topics:
  - http
  - server
  - tool
  - mockzilla

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.44.0'
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Interface
  plugin_platform_interface: ^2.1.8
  collection: ^1.19.1

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0
