package com.apadmi.mockzilla.codegen.file_builders.typescript

import com.apadmi.mockzilla.codegen.data.EndpointSpec
import com.apadmi.mockzilla.codegen.data.ExampleResponse
import com.apadmi.mockzilla.codegen.file_builders.dart.toEndpointName

fun generateTypescriptSource(endpoints: Array<EndpointSpec>): String {
    val buffer = StringBuffer()
    buffer.appendLine("// GENERATED CODE")
    buffer.appendLine("// Generated by Mockzilla.")
    buffer.appendLine()
    buffer.appendLine("import { HttpMethod, type MockzillaConfig } from 'react-native-mockzilla'\n")
    buffer.appendLine()

    buffer.appendLine("export const mockConfig: MockzillaConfig =")
    buffer.appendLine("{")
    // TODO: do we need this?
    buffer.appendLine("  port: 8083")
    buffer.appendLine("  endpoints: [")

    for (endpoint in endpoints) {
        buffer.appendLine(endpointFragment(endpoint))
    }
    buffer.appendLine("  ],")
    buffer.appendLine("};")
    

    return buffer.toString()
}

// TODO: check that this key works
internal fun endpointFragment(e: EndpointSpec): String = """
    {
      key: '${(e.method.name.uppercase() + e.path.replace("/", " ")).toEndpointName()}'
      name: '${(e.method.name.uppercase() + e.path.replace("/", " ")).toEndpointName()}',
      endpointMatcher: (request) =>
          request.method === HttpMethod.${e.method.name} &&
          request.uri.endsWith('${e.path}'),
      defaultHandler: (request) => ${responseExpression(e.successResponse)},
      errorHandler: (request) => ${responseExpression(e.errorResponse)},
      dashboardOptionsConfig: {
        presets: [${e.otherResponses.joinToString(",") { presetFragment(it) }}],
      }
    },"""

internal fun presetFragment(r: ExampleResponse): String = """
          {
            name: '${r.name}',
            description: null,
            response: ${responseExpression(r)},
          }"""

// TODO: we do nothing with headers rn
internal fun responseExpression(v: ExampleResponse): String {
    return "{statusCode: ${v.statusCode}, body: '${v.bodyValue}'}"
}

// TODO: test whether these are needed for RN
//internal fun String.toEndpointName(): String {
//    return escapeForDartLiteral().replace("*", " ").replace(":", " ")
//}
//
//internal fun String.escapeForDartLiteral(): String {
//    return replace("\\", "\\\\")
//        .replace("'", "\\'")
//        .replace("\$", "\\\$")
//        .replace("\n", " ")
//        .replace("\r", "\\r")
//}
//
//internal fun String.escapeJsonForDartLiteral(): String {
//    return replace("'", "\\'").replace("\$", "\\\$")
//}
//
