// Mocks generated by Mockito 5.4.5 from annotations
// in mockzilla_android/test/callback_provider/callback_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:mockzilla_platform_interface/src/models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDashboardOptionsConfig_1 extends _i1.SmartFake
    implements _i2.DashboardOptionsConfig {
  _FakeDashboardOptionsConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMockzillaHttpResponse_2 extends _i1.SmartFake
    implements _i2.MockzillaHttpResponse {
  _FakeMockzillaHttpResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$EndpointConfigCopyWith_3<$Res> extends _i1.SmartFake
    implements _i2.$EndpointConfigCopyWith<$Res> {
  _Fake$EndpointConfigCopyWith_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$MockzillaHttpRequestCopyWith_4<$Res> extends _i1.SmartFake
    implements _i2.$MockzillaHttpRequestCopyWith<$Res> {
  _Fake$MockzillaHttpRequestCopyWith_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EndpointConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockEndpointConfig extends _i1.Mock implements _i2.EndpointConfig {
  @override
  String get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#key),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#key),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get shouldFail => (super.noSuchMethod(
        Invocation.getter(#shouldFail),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Duration get delay => (super.noSuchMethod(
        Invocation.getter(#delay),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#delay),
        ),
        returnValueForMissingStub: _FakeDuration_0(
          this,
          Invocation.getter(#delay),
        ),
      ) as Duration);

  @override
  int get versionCode => (super.noSuchMethod(
        Invocation.getter(#versionCode),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool Function(_i2.MockzillaHttpRequest) get endpointMatcher =>
      (super.noSuchMethod(
        Invocation.getter(#endpointMatcher),
        returnValue: (_i2.MockzillaHttpRequest request) => false,
        returnValueForMissingStub: (_i2.MockzillaHttpRequest request) => false,
      ) as bool Function(_i2.MockzillaHttpRequest));

  @override
  _i2.DashboardOptionsConfig get dashboardOptionsConfig => (super.noSuchMethod(
        Invocation.getter(#dashboardOptionsConfig),
        returnValue: _FakeDashboardOptionsConfig_1(
          this,
          Invocation.getter(#dashboardOptionsConfig),
        ),
        returnValueForMissingStub: _FakeDashboardOptionsConfig_1(
          this,
          Invocation.getter(#dashboardOptionsConfig),
        ),
      ) as _i2.DashboardOptionsConfig);

  @override
  _i2.MockzillaHttpResponse Function(_i2.MockzillaHttpRequest)
      get defaultHandler => (super.noSuchMethod(
            Invocation.getter(#defaultHandler),
            returnValue: (_i2.MockzillaHttpRequest request) =>
                _FakeMockzillaHttpResponse_2(
              this,
              Invocation.getter(#defaultHandler),
            ),
            returnValueForMissingStub: (_i2.MockzillaHttpRequest request) =>
                _FakeMockzillaHttpResponse_2(
              this,
              Invocation.getter(#defaultHandler),
            ),
          ) as _i2.MockzillaHttpResponse Function(_i2.MockzillaHttpRequest));

  @override
  _i2.MockzillaHttpResponse Function(_i2.MockzillaHttpRequest)
      get errorHandler => (super.noSuchMethod(
            Invocation.getter(#errorHandler),
            returnValue: (_i2.MockzillaHttpRequest request) =>
                _FakeMockzillaHttpResponse_2(
              this,
              Invocation.getter(#errorHandler),
            ),
            returnValueForMissingStub: (_i2.MockzillaHttpRequest request) =>
                _FakeMockzillaHttpResponse_2(
              this,
              Invocation.getter(#errorHandler),
            ),
          ) as _i2.MockzillaHttpResponse Function(_i2.MockzillaHttpRequest));

  @override
  _i2.$EndpointConfigCopyWith<_i2.EndpointConfig> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$EndpointConfigCopyWith_3<_i2.EndpointConfig>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub:
            _Fake$EndpointConfigCopyWith_3<_i2.EndpointConfig>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$EndpointConfigCopyWith<_i2.EndpointConfig>);
}

/// A class which mocks [MockzillaLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockzillaLogger extends _i1.Mock implements _i2.MockzillaLogger {
  @override
  void log(
    _i2.LogLevel? level,
    String? message,
    String? tag,
    Exception? exception,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            level,
            message,
            tag,
            exception,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockzillaHttpRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockzillaHttpRequest extends _i1.Mock
    implements _i2.MockzillaHttpRequest {
  @override
  String get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#uri),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#uri),
        ),
      ) as String);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  String get body => (super.noSuchMethod(
        Invocation.getter(#body),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#body),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#body),
        ),
      ) as String);

  @override
  _i2.HttpMethod get method => (super.noSuchMethod(
        Invocation.getter(#method),
        returnValue: _i2.HttpMethod.get,
        returnValueForMissingStub: _i2.HttpMethod.get,
      ) as _i2.HttpMethod);

  @override
  _i2.$MockzillaHttpRequestCopyWith<_i2.MockzillaHttpRequest> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue:
            _Fake$MockzillaHttpRequestCopyWith_4<_i2.MockzillaHttpRequest>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub:
            _Fake$MockzillaHttpRequestCopyWith_4<_i2.MockzillaHttpRequest>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$MockzillaHttpRequestCopyWith<_i2.MockzillaHttpRequest>);
}
