fastlane_require 'dotenv'

Dotenv.load(".env", ".secret.env")

## See `fastfiles` directory for individual iOS and Android fastfiles
Dir["./fastfiles/*"].each {|file| import file }

before_all do |lane, options|
    lane_context[:repo_root] = sh("git rev-parse --show-toplevel").strip
end

lane :combined_pull_request do    

    # Library
    Fastlane::LaneManager.cruise_lane("ios", "lib_pull_request", {})
    Fastlane::LaneManager.cruise_lane("android", "lib_pull_request", {})

    publish_to_maven_local
end