fastlane_require 'dotenv'

Dotenv.load(".env", ".secret.env")

## See `fastfiles` directory for individual iOS and Android fastfiles
Dir["./fastfiles/*"].each {|file| import file }

before_all do |lane, options|
    lane_context[:repo_root] = sh("git rev-parse --show-toplevel").strip
end

lane :combined_pull_request do    
    # Management UI
    Fastlane::LaneManager.cruise_lane("android", "management_ui_pull_request", {})

    # Documentation
    generate_docs

    # Library
    Fastlane::LaneManager.cruise_lane("ios", "lib_pull_request", {})
    Fastlane::LaneManager.cruise_lane("android", "lib_pull_request", {})
    publish_to_maven_local

    # Pure Android Demo
    Fastlane::LaneManager.cruise_lane("android", "demo_android_pull_request", {})
    
    # Pure iOS Demo
    Fastlane::LaneManager.cruise_lane("ios", "demo_ios_pull_request", {})
    
    # KMM Demo
    Fastlane::LaneManager.cruise_lane("ios", "demo_kmm_pull_request", {})
    Fastlane::LaneManager.cruise_lane("android", "demo_kmm_pull_request", {})
end