name: mockzilla_android
description: The Android implementation for the mockzilla plugin.
# x-release-please-start-version
version: 2.0.0
# x-release-please-end
homepage: https://mockzilla.apadmi.dev/
repository: https://github.com/Apadmi-Engineering/Mockzilla
issue_tracker: https://github.com/Apadmi-Engineering/Mockzilla/issues
documentation: https://mockzilla.apadmi.dev/
topics:
  - http
  - server
  - tool
  - mockzilla

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

flutter:
  plugin:
    implements: mockzilla
    platforms:
      android:
        dartPluginClass: MockzillaAndroid
        package: com.apadmi.mockzilla
        pluginClass: MockzillaAndroidPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  mockzilla_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.6.0
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4
