site_name: Mockzilla
site_url: https://mockzilla.apadmi.dev/
repo_url: https://github.com/Apadmi-Engineering/Mockzilla
copyright: Copyright &copy; 2025 Apadmi Ltd
theme:
  logo: "img/icon.svg"
  favicon: "img/favicon.ico"
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
      accent: custom
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
plugins:
  - search
  - macros
extra_css:
  - stylesheets/extra.css
nav:
  - index.md
  - Docs:
    - quick-start.md
    - endpoints.md
    - Advanced:
      - additional_config.md
      - browser_stack.md
      - snapshots.md
    - Configuration at Runtime:
      - desktop/overview.md
      - mobile_ui.md
      - presets.md
  - Contributing:
      - contributing.md
      - Desktop App: desktop_contributing.md
      - Documentation: documentation.md
      - Flutter: flutter_contributing.md
  - Api Reference:
      ./dokka/index.html
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
hooks:
  - custom_hooks.py