site_name: Mockzilla
site_url: https://example.com/
repo_url: https://github.com/Apadmi-Engineering/Mockzilla
theme:
  palette:
    scheme: slate
    primary: deep orange
    accent: deep orange
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
plugins:
  - search
  - macros
nav:
  - Home:
    - index.md
    - endpoints.md
    - additional_config.md
    - browser_stack.md
    - Web:
        - Web Interface: web_interface.md
  - Contributing:
      - contributing.md
      - Documentation: documentation.md
  - Api Reference:
      ./dokka/index.html
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js