/**
 * This file is autogenerated by https://m3.material.io/theme-builder
 */

@file:Suppress(
    "MAGIC_NUMBER",
    "VARIABLE_NAME_INCORRECT_FORMAT",
    "LONG_NUMERICAL_VALUES_SEPARATED"
)

package com.apadmi.mockzilla.ui.ui.common.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import com.apadmi.mockzilla.ui.ui.common.components.PreviewSurface
import com.apadmi.mockzilla.ui.ui.common.widgets.debug.DebugColorsWidget
import org.jetbrains.compose.ui.tooling.preview.Preview

// Seed color is #4ECED8
val md_theme_light_primary = Color(0xFF00696F)
val md_theme_light_onPrimary = Color(0xFF9df0f8)
val md_theme_light_primaryContainer = Color(0xFF4ECED8)
val md_theme_light_onPrimaryContainer = Color(0xFF321300)
val md_theme_light_secondary = Color(0xFF4A6365)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8EA)
val md_theme_light_onSecondaryContainer = Color(0xFF324B4D)
val md_theme_light_tertiary = Color(0xFF616133)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE7E5AC)
val md_theme_light_onTertiaryContainer = Color(0xFF1D1D00)
val md_theme_light_error = Color(0xFF9F3B28)
val md_theme_light_errorContainer = Color(0xFFBF533D)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFFBFFFF)
val md_theme_light_background = Color(0xFFF1F1F1)
val md_theme_light_onBackground = Color(0xFF1C1B1B)
val md_theme_light_surface = Color(0xFFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1B1B)
val md_theme_light_surfaceVariant = Color(0xFFFDF8F8)
val md_theme_light_onSurfaceVariant = Color(0xFF1C1B1B).copy(alpha = 0.8f)
val md_theme_light_surface_container = Color(0xFFF3F3F5)
val md_theme_light_outline = md_theme_light_secondary.copy(alpha = 0.1f)
val md_theme_light_inverseOnSurface = Color(0xFFF4F0EF)
val md_theme_light_inverseSurface = Color(0xFF313030)
val md_theme_light_inversePrimary = Color(0xFFFFB5A0)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFDAF0F2)
val md_theme_light_outlineVariant = Color(0xFFD7C2B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4ECED8)
val md_theme_dark_onPrimary = md_theme_light_onPrimary
val md_theme_dark_primaryContainer = Color(0xFF286B70)
val md_theme_dark_onPrimaryContainer = Color(0xFFE5E2E1)
val md_theme_dark_secondary = Color(0xFFA5E1E6)
val md_theme_dark_onSecondary = Color(0xFF432B1C)
val md_theme_dark_secondaryContainer = Color(0xFF454E4F)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_tertiary = Color(0xFFCBC992)
val md_theme_dark_onTertiary = Color(0xFF323209)
val md_theme_dark_tertiaryContainer = Color(0xFF49491E)
val md_theme_dark_onTertiaryContainer = Color(0xFFE7E5AC)
val md_theme_dark_error = Color(0xFFFFB4A5)
val md_theme_dark_errorContainer = Color(0xFFE36E56)
val md_theme_dark_onError = Color(0xFF630F02)
val md_theme_dark_onErrorContainer = Color(0xFF480600)
val md_theme_dark_background = Color(0xFF1A1A1A)
val md_theme_dark_onBackground = Color(0xFFE5E2E1)
val md_theme_dark_surface = Color(0xFF262626)
val md_theme_dark_onSurface = Color(0xFFE5E2E1)
val md_theme_dark_surfaceVariant = Color(0xFF262626)
val md_theme_dark_onSurfaceVariant = Color(0xFFE5E2E1).copy(alpha = 0.8f)
val md_theme_dark_outline = md_theme_dark_secondary.copy(alpha = 0.1f)
val md_theme_dark_inverseOnSurface = Color(0xFF313030)
val md_theme_dark_inverseSurface = Color(0xFFE5E2E1)
val md_theme_dark_inversePrimary = Color(0xFFAB350F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB689)
val md_theme_dark_outlineVariant = Color(0xFF52443C)
val md_theme_dark_scrim = Color(0xFF000000)

val httpStatusCode_1xx = Color(0xFF0D6EFD)
val httpStatusCode_2xx = Color(0xFF198754)
val httpStatusCode_3xx = Color(0xFFA69011)
val httpStatusCode_4xx = Color(0xFFFFA500)
val httpStatusCode_5xx = Color(0xFFDC3545)
val httpStatus_fallback = Color(0xFFAD46FF)

val theme_warning_background = Color(0xFFFFD129)
val theme_accent = Color(0xFF4ECED8)
val theme_success = Color(0xFF4ED887)
val theme_warning = Color(0xFFCCD84E)
val theme_background_dark = Color(0xFF0D0D0D)

@Preview
@Composable
fun DebugColorsWidgetPreview() = PreviewSurface {
    DebugColorsWidget()
}
