on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

name: Release-Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: release-please-action
          command: release-pr
      - name: Deploy package to Maven Central
        env:
          releases_created: ${{ steps.release.outputs.releases_created }}
          release_created: ${{ steps.release.outputs.release_created }}
          prs_created: ${{ steps.release.outputs.prs_created }}
          all: ${{  toJSON(steps.release.outputs) }}
        run: |
          echo "Testing releases_created: $releases_created"
          echo "Testing release_created: $release_created"
          echo "Testing prs_created: $prs_created"
          echo "Testing prs_created: $all"
      - name: Trigger Deploy Binaries workflow (snapshots only)
        if: ${{ !steps.release.outputs.releases_created && steps.release.outputs.prs_created }}
        run: gh workflow run action_deploy_binaries.yml --ref release-please--branches--develop--components--release-please-action