name: Deploy Binaries

on: 
  workflow_dispatch:
  push:
    tags:
      - v**


jobs:
  deploy:
    environment: production
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Install dependencies
        run: bundle install
      - name: Deploy package to Maven Central
        run: | 
          export GPG_TTY=$(tty)
          bundle exec fastlane publish_to_maven
        env:
          GPG_PASSPHRASE:  ${{ secrets.GPG_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_KEY: ${{ secrets.OSSRH_KEY }}
      - name: Deploy package to Github for SPM & Cocapods
        run: bundle exec fastlane ios publish_swift_package
        env:
          IOS_DEPLOY_URL: ${{ secrets.IOS_DEPLOY_URL }}
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
          command: github-release
