name: Combined Pull Request

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: fastlane combined_pull_request
      - name: Validate Swagger and OpenAPI using Swagger CLI
        uses: mbowman100/swagger-validator-action@2.0
        with:
          files: webapi.yaml
    env:
      PR: true
      GIT_REPOSITORY_URL: ${{ github.repositoryUrl }}