name: Publish to `mockzilla` pub.dev

on:
  workflow_dispatch:
  push:
    tags:
    - flutter_mockzilla-v**

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1.8.1
    with:
      working-directory: FlutterMockzilla/mockzilla
      environment: production