name: Publish to `mockzilla_web` pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - flutter_mockzilla_web-v**

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    runs-on: macos-26
    permissions:
      id-token: write
    environment: production
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install dependencies
        run: bundle install
      - name: Download JS assets
        run: |
          export GPG_TTY=$(tty)
          bundle exec fastlane download_mockzilla_js_assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: '3.41.9'
          channel: 'stable'
      - run: cd FlutterMockzilla/mockzilla_web; flutter pub get
      - name: Publish
        run: cd FlutterMockzilla/mockzilla_web; flutter pub publish --force
