name: Publish react-native-mockzilla to npm

on:
  workflow_dispatch:
  push:
    tags:
      - react-native-mockzilla-v**

jobs:
  publish:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ReactNativeMockzilla/.nvmrc
      - name: Install dependencies
        run: yarn install --immutable
        working-directory: ReactNativeMockzilla
      - name: Setup fastlane
        run: bundle install
      - name: Publish to npm
        run: bundle exec fastlane react_native_publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
