name: Deploy Desktop app

on:
  workflow_dispatch:
  push:
    tags:
      - mockzilla-management-ui-v**

env:
  MAC_CERTIFICATE_PATH: "./osx_build_certificate.p12"
  MAC_SIGNING_KEY_PATH: "./osx_signing_key.p12"
  APPLE_NOTARIZATION_KEY_PATH: "./apple_notarization_key.p8"

jobs:
  deploy_desktop:
    environment: production
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install the Apple certificate and provisioning profile
        env:
          MAC_SIGNING_CERT: ${{ secrets.MAC_SIGNING_CERT }}
          MAC_SIGNING_KEY: ${{ secrets.MAC_SIGNING_KEY }}
          APPLE_NOTARIZATION_KEY: ${{ secrets.APPLE_NOTARIZATION_KEY }}
        run: |
          echo -n "$MAC_SIGNING_CERT" | base64 --decode > $MAC_CERTIFICATE_PATH
          echo -n "$MAC_SIGNING_KEY" | base64 --decode > $MAC_SIGNING_KEY_PATH
          echo -n "$APPLE_NOTARIZATION_KEY" | base64 --decode > $APPLE_NOTARIZATION_KEY_PATH
      - name: Build Jar
        run: ./gradlew :mockzilla-management-ui:jvmJar
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v14.3
        env:
          MAC_SIGNING_KEY_PASSWORD: ${{ secrets.MAC_SIGNING_KEY_PASSWORD }}
          APPLE_NOTARIZATION_KEY_ID: ${{ secrets.APPLE_NOTARIZATION_KEY_ID }}
          APPLE_NOTARIZATION_ISSUER_ID: ${{ secrets.APPLE_NOTARIZATION_ISSUER_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: make copied-site
          extra_flags: -f ci.conveyor.conf
          signing_key: ${{ secrets.CONVEYOR_ROOT_KEY }}
          agree_to_license: 1
