name: Deploy Binaries

on: 
  workflow_dispatch:
  push:
    branches:
      - release-please--branches--develop--components--release-please-action
    tags:
      - mockzilla-v**
env:
  is_snapshot: ${{ github.ref_type == 'branch' }}

jobs:
  deploy:
    environment: production
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Install dependencies
        run: bundle install
      - name: Deploy package to Maven Central
        run: | 
          echo "is_snapshot: $is_snapshot"
          export GPG_TTY=$(tty)
          bundle exec fastlane publish_to_maven is_snapshot:$is_snapshot
        env:
          GPG_PASSPHRASE:  ${{ secrets.GPG_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_KEY: ${{ secrets.OSSRH_KEY }}
      - name: Deploy package to Github for SPM & Cocoapods
        run: bundle exec fastlane ios publish_swift_package is_snapshot:$is_snapshot
        env:
          IOS_DEPLOY_URL: ${{ secrets.IOS_DEPLOY_URL }}
      - uses: googleapis/release-please-action@v4
        with:
          if: ${{ !env.is_snapshot }}
          release-type: simple
          skip-github-pull-request: true
