name: Combined Pull Request

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1' 
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Fetch develop branch so screenshotbot can access it
        run: |
          git fetch origin develop
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          pip install --upgrade setuptools 
          pip install -r docs/requirements.txt
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'
      - run: |
          bundle install
          bundle exec fastlane combined_pull_request
      - name: Validate Swagger and OpenAPI using Swagger CLI
        uses: mbowman100/swagger-validator-action@2.0
        with:
          files: webapi.yaml
    env:
      PR: true
      GIT_REPOSITORY_URL: ${{ github.repositoryUrl }}
      SCREENSHOTBOT_API_KEY:  ${{ secrets.SCREENSHOTBOT_API_KEY }}
      SCREENSHOTBOT_API_SECRET: ${{ secrets.SCREENSHOTBOT_API_SECRET }}